
version: 2

models:
  - name: time_of_day_visitor
    description: "count monthly visitor"
    columns:
      - name: time_of_day
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: last_30_days_visitor
    description: "count visitor based on district"
    columns:
      - name: district
        description: "The primary key for this table"
        tests:
          - unique
